### PR TITLE
Add Util.map

### PR DESCRIPTION
**Pull request by tofuness**
Same as Processing's `map` function.

### CODE REVIEW

**Comment by tofuness** [comment]
🙈 Ping @williamngan

**Comment by williamngan** [comment]
Thanks @tofuness. This would be a good addition. A couple comments:

- Would be good to check for division by zero when min1 == max1. I think something like 
`if (min1 == max1) then return ( (n-min1) / min1 ) * (max2-min2) + min2` may work. So that it will return a reasonable value instead of "Infinity". What do you think?

- Would prefer another function name like "mapToRange", since I think most people would think of "map" as functional programming's map and reduce.

- Minor style suggestion: would prefer brackets around ( `(n-min1) / (max1-min1)` ) * ... for clarity.

**Comment by tofuness** [comment]
@williamngan

> Would be good to check for division by zero [...]

1. Maybe we should just throw an error if `min1 == min2`? I personally think that the function shouldn't accept a degenerate starting interval because it doesn't feel right to try and map `[min1, max1] = min1` to `[min2, max2]`.

2.  `mapToRange` sounds good to me.
3. I agree on adding the parentheses.

Also, isn't there an infinite number of ways to map `min1` to `[min2, max2]` 😅?

**Comment by williamngan** [comment]
Sounds good. I think throwing an error makes sense -- easier to debug than
getting Infinity silently.

Thanks!

**Comment by tofuness** [comment]
Made the changes and added some tests. Let me know if I missed anything.

**Comment by williamngan** [comment]
Thank you @tofuness 👍

**Pull request merged**
